{
  "model": [
    # "NCA",
    # "GCN",
    # "MLP",
    "FixedBfsNCA",
    # "BfsNCA",
  ],

  "n_layers": [
    6,
    # 64,
  ],

  # How often to calculate the loss.
  "loss_interval": [
    null,
    # 16,
    # 32,
    # 64,
  ],

  "n_hid_chan": [
    6,
    # 10,
    # 24,
    # 48,
    # 96,
  ],

  "shared_weights": [
    True,
    # False,
  ],

  "skip_connections": [
    True,
    # False,
  ],

  "cut_conv_corners": [
    # True,
    False,
  ],

  # Whether to enable the (bug/fix) that limits the gradients accumulated to the last few layers of the network. 
  # Presumably only valid when using shared weights for all layers. Faster, but (persumably) less stable.
  "sparse_update": [
    # True,
    False,
  ],

  "minibatch_size": [
    32,
  ],

  "n_data": [
    # 256,
    512,
  ]

}