{
  "model": [
    "NCA",
    # "GCN",
    # "MLP",
  ],

  "n_hid_chan": [
    24,
    # 48,
    # 96,
  ],

  "shared_weights": [
    True,
    # False,
  ],

  # How often to calculate the loss.
  "loss_interval": [
    # 16,
    # 32,
    64,
  ],

  "skip_connections": [
    # True,
    False,
  ],

  # Whether to enable the (bug/fix) that limits the gradients accumulated to the last few layers of the network. 
  # Presumably only valid when using shared weights for all layers. Faster, but (persumably) less stable.
  "sparse_update": [
    True,
    # False,
  ],

  "minibatch_size": [
    16,
  ],

}